/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d8dad9',
        'surface-bright': '#f8faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f2',
        'surface-container': '#eceeec',
        'surface-container-high': '#e6e9e7',
        'surface-container-highest': '#e1e3e1',
        'on-surface': '#191c1b',
        'on-surface-variant': '#41493e',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
        outline: '#717a6d',
        'outline-variant': '#c0c9bb',
        'surface-tint': '#2a6b2c',
        primary: '#00450d',
        'on-primary': '#ffffff',
        'primary-container': '#1b5e20',
        'on-primary-container': '#90d689',
        'inverse-primary': '#91d78a',
        secondary: '#8b5000',
        'on-secondary': '#ffffff',
        'secondary-container': '#ff9800',
        'on-secondary-container': '#653900',
        tertiary: '#264300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#365c00',
        'on-tertiary-container': '#9dd65b',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#acf4a4',
        'primary-fixed-dim': '#91d78a',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#0c5216',
        background: '#f8faf8',
        'on-background': '#191c1b',
        'surface-variant': '#e1e3e1',
        'status-active': '#2E7D32',
        'status-warning': '#ED6C02',
        'status-error': '#D32F2F',
        'status-locked': '#455A64',
        'status-future': '#0288D1',
        'wallet-credit': '#2E7D32',
        'wallet-debit': '#D32F2F',
      },
      fontFamily: {
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
        hanken: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
